---
---
/* FILE WLLL BE GENERATED BY JEKYLL. */
var GLOSSES = {
{% for obj in site.data.glosses %}
{% assign name = obj[0] %}
{% assign gloss = obj[1] %}
    "{{ name }}": {
        gloss: parser.parse("{{ gloss.gloss | strip_newlines }}"),
        translation: "{{ gloss.trans }}",
    {% if gloss.lit %}
        literal: "{{ gloss.lit }}",
    {% else %}
        literal: null
    {% endif %}
    },
{% endfor %}
};
