/**
 *
 * Adds a gloss HTML element, similar to a <abbr> or <span>.
 *
 * By default, it's <x-gloss>, but this can be changed by providing a name to
 * the XGloss(), which will install it.
 */
(function (name) {
    'use strict';

    /* Default name if none chosen. */
    if (name === undefined) {
        name = 'x-gloss';
    }

    /**
     * Taken from <http://en.wikipedia.org/wiki/List_of_glossing_abbreviations>.
     */
    var glossToName = {
        0: "zero (null), covert form\n(such as gender in a language where the word doesn't show it)",
        1: "first person",
        2: "second person",
        3: "third person",
        '-e': "(used to form various -essive cases)",
        '-l': "(used to form various -lative cases)",
        '-t': "trigger (used for at, pt)",
        '-z': "-(al)izer (e.g. trz transitivizer)",
        A: "agent-like argument of canonical transitive verb",
        O: "patient-like argument (object) of canonical transitive verb (= P)",
        P: "patient-like argument of canonical transitive verb (= O)",
        S: "single argument of canonical intransitive verb (cf cit)",
        abe: "abessive case (aka caritive case or privative case: 'without')",
        abl: "ablative case ('from')",
        abs: "absolutive case",
        acc: "accusative case",
        accom: "accompanier",
        act: "active voice, actor role",
        ade: "adessive case ('at'; more specific than loc)",
        adj: "adjective",
        adm: "admonitive mood (warning)",
        adv: "adverb(ial), adverbial case",
        aff: "affirmative mood",
        ag: "agentive case (cf act)",
        agr: "agreement",
        agt: "agentive case (cf act)",
        al: "allocutive agreement",
        alien: "alienable possession",
        all: "allative case ('to')",
        alloc: "allocutive agreement",
        an: "animate gender (cf r)",
        and: "andative (going towards: cf venitive)",
        ant: "anterior tense (used for prf in some traditions)",
        ante: "antessive case ('before')",
        antic: "anticausative",
        antip: "antipassive voice",
        aor: "aorist (= pfv or pst.pfv)",
        ap: "antipassive voice",
        apl: "applicative voice",
        app: "apposition",
        appl: "applicative voice",
        appr: "apprehensive mood",
        aprx: "approximative",
        art: "article",
        asp: "aspect",
        ass: "associative case (= com), assumptive mood, assertive",
        at: "agent trigger (= av agent voice)",
        att: "attenuative; attributive (= attr)",
        aud: "auditory evidential",
        aug: "augmentative",
        aux: "auxiliary verb",
        b: "core benefactive",
        be: "'be' verb (a conflation of exist and cop)",
        ben: "benefactive case ('for')",
        c: "common gender; complementizer",
        cap: "(cap)ability, modal case",
        cau: "causative",
        caus: "causative",
        cent: "centric case",
        cf: "counterfactual conditional",
        circ: "circumfix",
        cit: "citation form",
        cl: "classifier",
        clf: "classifier",
        cmpl: "complementizer",
        cnj: "conjunction (= conj)",
        cnsq: "consequential",
        cntr: "contrastive",
        col: "collective plural",
        com: "comitative case ('together with')",
        comp: "comparative; complementizer",
        compl: "completive aspect",
        conc: "concessive",
        cond: "conditional mood",
        conj: "conjunction (= cnj)",
        conn: "connective particle",
        cont: "continuative aspect",
        cop: "copula",
        cor: "coreference",
        cpl: "completive aspect",
        cras: "crastinal tense ('tomorrow')",
        crs: "current relevance marker (as in the perfect)",
        ctn: "continuative aspect",
        cvb: "converb",
        d: "core dative case",
        dat: "dative case",
        de: "different event, change of event (cf ds)",
        dec: "declarative mood",
        decl: "declarative mood",
        def: "definite",
        dei: "deixis, deictic",
        deix: "deixis, deictic",
        del: "delative case ('off of'), deliberative mood",
        dem: "demonstrative",
        deo: "deontic mood",
        dep: "dependent (as in dep.fut)",
        des: "desiderative mood",
        desi: "desiderative mood",
        dest: "destinative aspect",
        det: "determiner",
        detr: "detransitive",
        dh: "motion downhill, seaward (cf dr)",
        dim: "diminutive",
        dir: "direct evidential (= exp); directional (= lat); direct case",
        disj: "disjunction",
        dist: "distal demonstrative",
        distr: "distributive case",
        ditr: "ditransitive",
        dlm: "delimited",
        dm: "discourse marker",
        'do': "direct object",
        dr: "motion downriver (cf dh)",
        ds: "different-subject (change of subject) marker (cf de)",
        du: "dual number",
        dub: "dubitative mood",
        dur: "durative aspect, continuous aspect",
        dy: "dyadic",
        dyad: "dyadic",
        dyn: "dynamic aspect",
        e: "epenthetic morpheme",
        ela: "elative case ('out of')",
        emp: "emphatic",
        epis: "epistemic mood, epistemic modality",
        erg: "ergative case",
        ess: "essive case",
        ev: "evidential",
        evid: "evidential",
        evit: "evitative case (= aversive case)",
        ex: "exclusive person",
        'ex.dur': "excessive duration",
        excl: "exclusive person",
        exclam: "exclamative",
        exh: "exhortative",
        exist: "existential ('there is')",
        exo: "exocentric case",
        exp: "experiential, eyewitness, = direct evidential",
        exper: "experiential, eyewitness, = direct evidential",
        expl: "expletive (dummy / meaningless form)",
        f: "feminine gender",
        fact: "factive evidential",
        fam: "familiar register (as the T–V distinction)",
        fem: "feminine gender",
        fin: "finite verb",
        fmr: "former, deceased",
        foc: "focus",
        form: "formal register (as the T–V distinction)",
        fp: "final particle (joshi)",
        fr: "frequentative aspect",
        freq: "frequentative aspect",
        fut: "future tense",
        g: "gender (G4 = the 4th gender)",
        gen: "genitive case",
        ger: "gerund",
        gno: "gnomic (generic) aspect",
        gt: "goal trigger (Austronesian; = gv goal voice)",
        hab: "habitual aspect",
        hbl: "humble register",
        hest: "hesternal tense ('yesterday')",
        hist: "historic(al), as in historical present or past historic tense",
        hod: "hodiernal tense ('today')",
        hon: "honorific",
        hort: "hortative,",
        hsy: "hearsay, reported evidential",
        hum: "human, anthropic gender (cf. hbl; r)",
        hyp: "hypothetical mood",
        i: "inflected",
        id: "identical (~ nid)",
        identif: "identifiable",
        ideo: "ideophone (≈ mim)",
        ignor: "ignorative",
        ill: "illative case ('into')",
        imm: "immediate, as in immediate imperative mood, near future tense",
        imp: "imperative mood",
        imperf: "imperfect (= pst.ipfv)",
        impr: "imprecative mood",
        imprec: "imprecative mood",
        imprs: "impersonal verb",
        'in': "inclusive person",
        inal: "inalienable possession",
        inan: "inanimate gender",
        incep: "inchoative aspect, inceptive aspect",
        inch: "inchoative aspect, inceptive aspect",
        incho: "inchoative aspect, inceptive aspect",
        incl: "inclusive person (= in)",
        ind: "indicative mood",
        indf: "indefinite",
        ine: "inessive case ('in')",
        inel: "inelative case ('from within')",
        inf: "infinitive",
        infer: "inferential evidential",
        infr: "inferential evidential",
        ins: "instrumental case",
        'int': "intensifier; interrogative (= q)",
        inten: "intentional",
        intr: "intransitive (covers an intransitive case for the S argument)",
        inv: "inverse",
        io: "indirect object",
        ipfv: "imperfective aspect (= npfv)",
        irr: "irrealis mood",
        is: "indirect speech",
        iter: "iterative aspect",
        jus: "jussive mood",
        l2: "second language (code-switching)",
        lat: "lative case (= mvmt, direction)",
        ld: "locative case + directional",
        lk: "linker",
        loc: "locative case (includes essive case)",
        log: "logophoric",
        m: "masculine gender",
        man: "manner",
        masc: "masculine gender",
        mid: "middle voice",
        mim: "mimetic (≈ ideo)",
        mir: "(ad)mirative",
        mod: "mood, modal, modal case",
        mom: "single action verb (not iterative)",
        mvt: "movement",
        n: "neuter gender",
        'n-': "non- (e.g. nsg non-singular, npst non-past, nf non-feminine)",
        ndef: "indefinite",
        neg: "negation, negative",
        neut: "neuter gender",
        nh: "non-human",
        nmz: "nominalizer/nominalization",
        nom: "nominative case",
        nomi: "nominalizer/nominalization",
        ns: "non-subject (Latin 'oblique case')",
        ntr: "intransitive (covers an intransitive case for the S argument)",
        num: "numeral",
        nz: "nominalizer/nominalization",
        ob: "object; objective case",
        obj: "object; objective case",
        obl: "oblique case",
        obv: "obviative",
        opt: "optative mood",
        p: "pre-, post- (p.hod prehodiernal)",
        pa: "paucal number",
        part: "participle (= ptcp,pcp); particle (= ptcl); partitive case (= ptv)",
        pas: "passive voice",
        pass: "passive voice",
        pat: "patientive (= und)",
        pau: "paucal number",
        pcp: "participle",
        peg: "pegative case (a special case for the giver)",
        per: "perlative case ('per', using)",
        perf: "perfect (= ret)",
        pers: "personal",
        pfv: "perfective aspect",
        pl: "plural",
        plu: "pluractional",
        plur: "pluractional",
        pm: "phrase marker, predicate marker",
        pn: "pronoun",
        po: "primary object",
        pol: "polite register",
        pos: "possessive marker",
        poss: "possessive marker",
        post: "postposition, postpositional case",
        poste: "postessive case ('after')",
        pot: "potential mood (a possible conditional)",
        pp: "past / passive participle",
        ppfv: "past perfective",
        ppp: "past passive participle",
        pr: "proper noun",
        prec: "precative mood (requests)",
        pred: "predicative",
        prep: "preposition, prepositional case",
        pres: "present tense",
        presp: "present participle",
        pret: "preterite (= pfv.pst)",
        prf: "perfect (= ret)",
        pro: "pronoun",
        prob: "probability",
        prog: "progressive aspect",
        proh: "prohibitive mood ('don't!')",
        prol: "prolative case (= via)",
        prop: "propositive mood",
        prosp: "prospective aspect",
        prot: "protasis",
        prox: "proximal/proximate",
        prs: "present tense",
        prsp: "prospective aspect",
        prt: "preterite (= pfv.pst)",
        pst: "past tense",
        pt: "patient trigger",
        ptc: "particle",
        ptcl: "particle",
        ptcp: "participle",
        ptv: "partitive case ('some of')",
        purp: "purposive",
        q: "question word or particle (= int)",
        quot: "quotative case or mood (marks quoted speech)",
        r: "rational gender (thinking beings)",
        real: "realis mood",
        rec: "recent past tense",
        recp: "reciprocal voice",
        ref: "referential",
        refl: "reflexive voice",
        rel: "relative(izer)",
        rem: "remote past tense",
        rep: "reported evidential (= hsy); repetitive (cf iter)",
        res: "resultative; resumptive",
        ret: "retrospective (synonym for 'perfect' in some traditions)",
        rfr: "referential",
        sbj: "subject",
        sbjv: "subjunctive mood",
        sbrd: "subordinator",
        se: "same event (cf ss)",
        sem: "semelfactive aspect ('once')",
        sens: "sensory evidential mood (= vis+aud",
        seq: "sequential",
        sg: "singular (but 1.sg = 1s, 3masc.sg = 3ms)",
        sgv: "singulative number",
        sim: "simultaneous aspect; similative",
        sjv: "subjunctive mood",
        spec: "specifier; speculative mood",
        sr: "subordinator",
        ss: "same-subject marker (cf se)",
        stat: "stative aspect, stative verb",
        stv: "stative aspect, stative verb",
        su: "subject",
        sub: "subject",
        sube: "subessive case ('under')",
        subl: "sublative case ('onto', 'down onto')",
        subord: "subordinator",
        subr: "subordinator",
        suc: "successive ('then')",
        'sup(l)': "superlative (supl); supine; supplicative",
        supe: "superessive case ('on')",
        tam: "tense, aspect, or mood",
        tel: "telic aspect (cf pfv)",
        temp: "temporal case",
        term: "terminative case",
        tns: "tense",
        top: "topic",
        tr: "transitive verb, transitive case (rare)",
        trans: "transitive verb, transitive case (rare)",
        transl: "translative case (becoming)",
        tri: "trial number",
        trn: "trans-numeral (neither sg nor pl)",
        tvf: "truth-value focus",
        u: "uninflected",
        uh: "motion uphill, inland (cf ur)",
        und: "undergoer role (cf pat)",
        ur: "motion upriver (cf uh)",
        usit: "usitative",
        v: "verb(al)",
        vb: "verb(al)",
        vbz: "verbalizer",
        vd: "verb, ditransitive",
        ven: "venitive (coming towards; cf andative)",
        ver: "veridical, veridical mood (a certain conditional)",
        vi: "verb, intransitive",
        via: "vialis case",
        vis: "visible, visual",
        vn: "verbal noun",
        voc: "vocative case",
        vol: "volitive mood",
        vt: "verb, transitive",
        'wh.q': "wh- question",
        zo: "zoic gender (animals)",
        '›': "direction of transitivity or possession\n(2›3 may mean 2 acts on 3; 1sg›sg may mean a 1sg possessor and a singular possessum)"
    };


    var XGloss = document.registerElement(name, {
        prototype: Object.create(HTMLSpanElement.prototype, {
            /**
             * Normalize and add a title attribute.
             */
            createdCallback: {
                value: function () {
                    var original = this.innerText;
                    var normalized = original.trim().toLowerCase();

                    this.innerText = normalized;

                    if (this.attributes.title) {
                        /* Do not attempt to set a title if it already exists. */
                        return;
                    }

                    if (!(normalized in glossToName)) {
                        /* Could not find the gloss. */
                        return;
                    }

                    this.setAttribute('title', glossToName[normalized]);
                }
            }
        })
    });

    XGloss.glossToName = glossToName;

    if (document && document.currentScript) {
        /* Assume we're a browser. */
        window.XGlossElement = XGloss;
        /* TODO: Cool stuff here. */
    }

    return XGloss;
}.call(this));
